django/workshop190130/workshop/surveys/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    
    
    ]

django/workshop190130/workshop/workshop/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django/workshop190130/workshop/surveys/models.py
from django.db import models

class Question(models.Model):
    title=models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

class Choice(models.Model):
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
    content=models.CharField(max_length=100)
    votes=models.IntegerField()

# Create your models here.

django/workshop190130/workshop/surveys/templates/Research.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

django/workshop190130/workshop/surveys/templates/Result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{question.title}}</h1>
    <ul>{%for choice in question.choice_set.all%}
    <li>{{choice.content}}:{{choice.votes}}</li>
    {%endfor%}
</ul>
</body>
</html>