django/tutorial/crud0418/crud0418/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

django/tutorial/crud0418/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.list, name ='list'),
    path('create/', views.create, name = 'create'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('<int:movie_id>/update/', views.update, name = 'update'),
    path('<int:movie_id>/delete/', views.delete, name = 'delete'),
    path('<int:movie_id>/comment/create', views.comment_create, name = 'comment_create'),
    path('<int:movie_id>/comment/<int:comment_id>/delete', views.comment_delete, name = 'comment_delete'),
    ]

django/tutorial/crud0418/accounts/models.py
from django.db import models

# Create your models here.

django/tutorial/crud0418/movies/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    title = models.TextField()

class Comment(models.Model):
    content = models.TextField()
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)

django/tutorial/crud0418/movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

django/tutorial/crud0418/accounts/views.py
from django.shortcuts import render

# Create your views here.

django/tutorial/crud0418/movies/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import MovieForm, CommentForm
from .models import Movie, Comment
from django.views.decorators.http import require_POST

# Create your views here.

def create(request):
    if request.method == 'POST':
        form = MovieForm (request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('/movies/{}/'.format(movie.id))
            #return redirect('movies:detail', movie.id) #movie_id = movie.id
            #'movies:detail', movie.id => /movies/1/, movie_id = 1
    else:
        form = MovieForm()
    # movie_form = MovieForm()
    return render(request, 'movies/form.html', {'form':form})
    
def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    form = CommentForm()
    return render(request, 'movies/detail.html', {'movie':movie, 'form':form})
    
def list(request):
    movies = Movie.objects.all()
    return render(request, 'movies/list.html', {'movies':movies})
    
def update(request, movie_id):
    movie = get_object_or_404(Movie, id = movie_id)
    
    if request.method=='POST':
        form = MovieForm(request.POST, instance = movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie_id)
    else:
        form = MovieForm(instance=movie)    
    return render(request, 'movies/form.html', {'form':form})
    
@require_POST    
def delete(request, movie_id):
    movie = get_object_or_404(Movie, id = movie_id)
    movie.delete()
    return redirect('movies:list')
    
@require_POST
def comment_create(request, movie_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.movie_id = movie_id
        comment.save()
    return redirect('movies:detail', movie_id)
    
@require_POST
def comment_delete(request, movie_id, comment_id):
    comment = get_object_or_404(Comment, id = comment_id)
    comment.delete()
    return redirect('movies:detail', movie_id)

django/tutorial/crud0418/accounts/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

django/tutorial/crud0418/movies/templates/movies/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Movie Create</h1>
    
    <form action = "" method="POST">
        {% csrf_token %}
        {{ movie_form }}
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>

django/tutorial/crud0418/movies/templates/movies/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Movie Detail</h1>
    <p>{{movie.id}}
    {{movie.title}}</p>
    <form action = "{% url 'movies:delete' movie.id %}" method = "POST">
        {% csrf_token %}
        <input type="submit" value="Delete"/>
    </form>
    <hr>
    {% for comment in movie.comment_set.all %}
    
    <li>{{ comment.content }}
        <form action = "{% url 'movies:comment_delete' movie.id comment.id %}" method = "POST">
            {% csrf_token %}
            <input type="submit" value="Delete"/>
        </form>
    </li>
    
    {% endfor %}
    <form action = "{% url 'movies:comment_create' movie.id %}" method = "POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value = "Submit"/>
    </form>
</body>
</html>

django/tutorial/crud0418/movies/templates/movies/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Movie Form</h1>
    <form method = "POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value = "Submit">
    </form>
</body>
</html>

django/tutorial/crud0418/movies/templates/movies/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>List</h1>
    <a href = "{% url 'movies:create' %}">New Movie</a>
    <ul>
        {% for movie in movies %}
    <li><a href = "{% url 'movies:detail' movie.id %}">{{movie.title}}</a></li>
    {% endfor %}</ul>
    
</body>
</html>