django/insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views

app_name = 'posts'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('<str:username>/', accounts_views.people, name='people'),
] 

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django/insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name = 'list'),
    path('explore/', views.explore, name = 'explore'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'), 
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_id>/like/', views.like, name='like'),
    ]

django/insta/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings 

# Create your models here.

def post_image_path(instance, filename):
    return 'posts/images/{}'.format(filename)
    
# def post_image_path(instance):
#     return f'posts/{instance.user.username}/{instance.content}.jpeg'

# def post_image_path(instance, filename):
#     return f'posts/{instance.user.username}/{filename}'

# def post_image_path(instance, filename): #instance와 filename은 꼭 있어야 함
#     return f'posts/images/{filename}'

# def post_image_path(instance, filename):
    # return 'posts/{}/{}'.format(instance.content, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    # image = models.ImageField(blank=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

class Image(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    file = ProcessedImageField(
        upload_to = post_image_path, #저장 위치
        processors = [ResizeToFill(600,600)], #처리할 작업 목록
        format = 'JPEG', #저장 포맷
        options = {'quality':90},
        ) #옵션
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    content = models.TextField()

django/insta/posts/forms.py
from django import forms
from .models import Post, Comment, Image

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', ]

class CommentForm(forms.ModelForm):
    content = forms.CharField(label = '', widget = forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Comment.'}))
    
    class Meta:
        model = Comment
        fields = ['content',]

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file',]
        
ImageFormSet = forms.inlineformset_factory(Post, Image, form=ImageForm, extra=3)

django/insta/posts/views.py
from django.shortcuts import render, redirect ,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import PostForm, CommentForm, ImageFormSet
from .models import Post, Comment
from django.db import transaction
from itertools import chain
from django.http import JsonResponse

# Create your views here.

def explore(request):
    posts = Post.objects.order_by('-id').all()
    comment_form = CommentForm()
    return render(request, 'posts/list.html', {'posts': posts, 'comment_form':comment_form})

@login_required
def list(request):
    # posts = Post.objects.order_by('-id').all()
    #1. 내가 follow 하고 있는 사람의 리스트를 가져 옴
    # followings = request.user.followings.all()
    followings = request.user.followings.values_list('id', flat = True)
    #2. followings 변수와 현재 user를 묶는다.
    followings = chain(followings, [request.user])
    #3. followings들이 작성한 Post들만 가져 옴
    posts = Post.objects.filter(user__in = followings).order_by('-id') #user__in을 통해 user의 리스트를 조건으로 정할 수 있음
    comment_form = CommentForm()
    return render(request, 'posts/list.html', {'posts': posts, 'comment_form':comment_form})

@login_required
def create(request):
    if request.method == 'POST':
        # request.POST <-{'content':'asdf', 'user_id':1} 이런 상태임
        #요청에 사용자 정보가 포함되어 있으면 악용될 수 있음
        post_form = PostForm(request.POST)
        image_formset = ImageFormSet(request.POST, request.FILES)
        if post_form.is_valid() and image_formset.is_valid():
            post = post_form.save(commit = False)
            post.user = request.user
            
        with transaction.atomic():
            #첫번째
            post.save() #실제 데이터베이스에 저장
            #두번째
            image_formset.instance = post
            image_formset.save() #실제 데이터베이스에 저장
            
            return redirect('posts:list')
    else:
        post_form = PostForm()
        image_formset = ImageFormSet()
    return render(request, 'posts/form.html', {'post_form': post_form, 'image_formset':image_formset,})

@login_required    
def update(request,post_id):
    post = get_object_or_404(Post, id = post_id)
    if post.user != request.user:
        return redirect('posts:list')
    
    if request.method =='POST':
        post_form = PostForm(request.POST, instance = post)
        image_formset = ImageFormSet(request.POST, request.FILES, instance=post)
        if post_form.is_valid() and image_formset.is_valid():
            post_form.save()
            image_formset.save()
            return redirect('posts:list')
    else:
        post_form = PostForm(instance=post)
        image_formset = ImageFormSet(instance=post)
    return render(request, 'posts/form.html',{'post_form':post_form, 'image_formset': image_formset})
    
@login_required
def delete(request, post_id):
    # post = Post.objects.get(pk=post_id)
    post=get_object_or_404(Post, id=post_id)
    if post.user != request.user:
        return redirect('posts:list')
    # if post.user == request.user:
    #   post.delete()
    post.delete()
    return redirect('posts:list')
    
@login_required
@require_POST
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_id
        comment.save()
    # return redirect('posts:list')
    return JsonResponse({
                         'id': comment.id,
                         'postId': post_id,
                         'username':comment.user.username,
                         'content': comment.content,
                         })

@require_http_methods(['GET', 'POST'])
def comment_delete(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    # if comment.user != request.user:
    #     return redirect('posts:list')
    if comment.user == request.user:
        comment.delete()
    return redirect('posts:list')
    
@login_required    
def like(request,post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.like_users.all():
        # 좋아요를 취소함
        post.like_users.remove(request.user)
        liked = False #좋아요를 취소 했는지 아닌지를 확인하기 위한 확인 변수
    else:
        # 좋아요를 클릭함
        post.like_users.add(request.user)
        liked = True
    
    # return redirect('posts:list') 이제 페이지를 넘겨줄 일이 없으므로 주석처리를 한다.
    return JsonResponse({'liked':liked, 'count':post.like_users.count()}) #import

django/insta/insta/templates/posts/_post.html
<div class="card" style="width: 18rem;">
  <div class="card-header">
    {% if post.user.profile.image %}
    <img src="{{post.user.profile.image.url}}" width = "25" alt="">
    {% endif %}
    <span><a href = "{% url 'people' post.user.username %}">{{ post.user.username }}</a></span>
  </div>
  <div id="post_{{ post.id }}" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    {% for image in post.image_set.all %}
     <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
  <img src="{{image.file.url}}" class="card-img-top" alt="{{ image.file }}">
  </div>
  {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#post_{{ post.id }}" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#post_{{ post.id }}" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  
  <div class="card-body">

      <i class="{% if user in post.like_users.all %}fas{% else %}far{% endif %} fa-heart like-button" data-id = "{{ post.id }}"></i>

    <p class = "card-text">
      <span id="like-count-{{post.id}}">{{ post.like_users.count }}</span>명이 좋아합니다.
      
    </p>
    <p class="card-text flex-between">{{post.content}}</p>
    {% if post.user == user %}
    <a href="{% url 'posts:update' post.id %}" class="btn btn-info">Edit</a>
    <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">Delete</a>
    {% endif %}
  </div>
  
  <div class = "card-body" id="comment-list-{{ post.id }}">
    {% for comment in post.comment_set.all %}
    <div class = "card-text">
      <strong><a href = "{% url 'people' comment.user.username %}">{{ comment.user.username }}</a> </strong> {{ comment.content }}
      {% if comment.user == user %}
      <a href="{% url 'posts:comment_delete' post.id comment.id %}">Del</a>
      {% endif %}
    </div>
  {% empty %}
  <!--<div class="card-text"> 댓글이 없습니다.</div>-->
  
  {% endfor %}
  {% if user.is_authenticated %}
  </div>
  
  <form action = "{% url 'posts:comment_create' post.id %}" method = "POST" class = "comment-form">
    {% csrf_token %}
    
  <div class="input-group">
    {{comment_form}}
    <div class="input-group-append">
      <input type = "submit" value = "Submit" class = "btn btn-primary"/>
    </div>
  </div>
  </form>
  {% endif %}
</div>

django/insta/insta/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block container %}

<h1>New Post</h1>

<form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    
    {% buttons %}
    <button type="submit" class = "btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock %}

django/insta/insta/templates/posts/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block container %}

<h1>Post Form</h1>

<form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    {{image_formset.as_p}}
    
    {% buttons %}
    <button type="submit" class = "btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock %}

django/insta/insta/templates/posts/list.html
{% extends 'base.html' %}

{%block container %}

<h1>Post List</h1>

<div class="row">

    {% for post in posts %}

    {% include 'posts/_post.html' %}
 
</div>
{% endfor %}

<script>
    const likeButtons = document.querySelectorAll('.like-button')
    likeButtons.forEach(function(button){//각 버튼에 대한 addEventListener를 위한 반복
        button.addEventListener('click', function(event){
            console.log(event)
            const postId = event.target.dataset.id //지정한 변수에는 data-id를 사용했었으므로
            axios.get(`/posts/${postId}/like/`)//요청을 보낼 주소(urls.py)
                    .then(function(response){
                        // console.log(response)
                        //response.data가 받은 obejct-> {liked: true, count: 1} 
                        document.querySelector(`#like-count-${postId}`).innerText = response.data.count
                        if(response.data.liked){
                            //i 태그에 대한 정보는 event.target에 들어 있음
                            event.target.classList.remove('far')//like-button에 지정한 클래스를 수정
                            event.target.classList.add('fas')
                        }else{
                            event.target.classList.remove('fas')//like-button에 지정한 클래스를 수정
                            event.target.classList.add('far')
                        }
                    })
        })
    })
    
    const commentForms = document.querySelectorAll('.comment-form')
    commentForms.forEach(function(form){
        form.addEventListener('submit', function(event){
            event.preventDefault()
            console.log(event)
            // event.target == form
            const data = new FormData(event.target)
            // Inspect FormData
            for (const item of data.entries()){
                console.log(item)
            }
            axios.post(event.target.action, data)
                    .then(function(response){
                        // console.log(response)
                        const comment = response.data
                        const commentList = document.querySelector(`#comment-list-${comment.postId}`)
                        const newComment = `<div class = "card-text">
                                              <strong><a href = "/${comment.username}/">${comment.username }</a> </strong> ${ comment.content }
                                              <a href="/posts/${comment.postId}/comments/${comment.id}/delete/">Del</a>
                                            </div>`
                        commentList.insertAdjacentHTML('beforeend',newComment)
                        event.target.reset()
                    })
        })
    })
</script>

{% endblock %}